# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/JwtInspector/JwtInspector.Core.csproj
      
    - name: Restore dependencies for Test Project
      run: dotnet restore src/JwtInspector.Tests/JwtInspector.Tests.csproj
      
    - name: Build
      run: dotnet build src/JwtInspector/JwtInspector.Core.csproj --no-restore
      
    - name: Build Test Project
      run: dotnet build src/JwtInspector.Tests/JwtInspector.Tests.csproj --no-restore
      
    - name: Test
      run: dotnet test src/JwtInspector.Tests/JwtInspector.Tests.csproj --no-build --verbosity normal
